language: android
sudo: required
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
env:
  global:
  - ANDROID_API=23
  - EMULATOR_API_LEVEL=16
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=5
  - secure: a8Ii0gbBEg2rwIvS/ZSH7HUuamfyP4/sFc84sEgI8+ruKhUrKARxVVSCQoW1UA5iXd/dvMkI2Y3kkYV44Q6NSrZy0uZylmW5Bv0fh0hgTiPQZ5iP2rn+Nx/IQCjTOqvoeMaSSUhd9BmOK6PtVXMCyI9oISoMSpwc0AxzxmcxCQw46P6wwfLz+BxCxZPeuO4AD/Itjy/J9jV0kWMYKrrT9zzQg53OjfGGRc/6AkIJe6J3eR8N1/JdTqce4gnFjKmMLDrrX0YM1IBpbtLtaklsd8z+H4tgUL0VnUNDLVeeepcaw5ZvUcrztdu9ikXmTslEO5vusj7a6LsPGMymYshsPpWZ3t2RKvRBYmatSRKdE1MEFAzM94O5fvCFC3xqqWNClnJuLolbR1qgqcEx5JhIe2P3vY/HT84XXHPEZjaJxC7kfHKWzIsIXKI++Q0o3qtGGziuo8SiSJA2sZ3PNEYdJKc2isHgQiXJ+FLwCNrTs3snggzvb2g4LLwx4i+IRxWJoYZJj7xJvPkd66aUoAVCesTjmqC+pgnf7XQaT98VRtnOoT30Ue1z5WQA64gJ1wgQrYqJV4Ye3JLNvy34lR4mTHY6Urgn+RV08G6gFxlkacv+bU4zAM6uln4QdC0WllWln1Q80ObwdxGTprU6EUm4WF714Bmd1qzhPym7bfFly6g=
  - secure: S9R7AxNrCmNzvImjXD0fDU4lDTk4x21M3VuKJOOnsTFljTsDlT7QlPPJFuv9LiNrqo2mVO5TnCWJYwCVYbvp15AQtzcmF4Ppf0SyDb2IgB7WjO7JAWDlhHhgGfAItI/LaeQy3malKScQ6FClFF/EyFl+afNoNxdGQQL9QmzFabIJ53S5otQs/sA87C2OnS33ROfRBI2H8ZXI8a1sn5Cz1lgHwe0UW9WpzQ1XAJR30hFEf657qu6UNcPtrTp6Aq3nTu4A/XBN91LT+QPexC+DggAMMR9sVF9aqfbOiOXQb/qYxk+wDkRNfLan/3GPzjlF/yaIGAYXSGwTSxYZANVB65/kfO711NXHI/DPxSmtKgU38bSdJC1gW7x5MYcEwKOYoOfS0Ojt8KZAFa38CrmiDqAC6bZrG+XV9tJBMFuvTTir4JqJxYd6Ad9zTICuB3x3DqCaFnwuITngiePFbGciktECgkL7rc9FpuM5PpbgDpWGES5dCKdSrlDap1HBgLfgOGzOBkrIOU58nBhuGAJ9Qj7bXIqZZvJUO+l/0/js1IbcAHuE4j/r8mogWIKHDWl/iGfWquCwYhg321/orf9D6PBQ2ac+LSSbcVCEF/pM1V+wsJ9Va+uvcJwncqp5znQkos7y2vla+Me7ORVjca4FUO7fuGgNdbjEaEK+1b8kH1E=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-adroid-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_7ed12be32546_key -iv $encrypted_7ed12be32546_iv
  -in google-services.json.enc -out Basic/google-services.json -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
before_script:
- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API_LEVEL
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
script:
- "./gradlew clean assembleDebug testDebugUnitTest"
- "./gradlew build jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- cp $TRAVIS_BUILD_DIR/myspecial.jks $HOME
- cd Basic/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/myspecial.jks
  -storepass $storepass -keypass $keypass Basic-release-unsigned.apk key0
- jarsigner -verify Basic-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS/zipalign -v 4 Basic-release-unsigned.apk
  my-special-way.apk"
deploy:
  provider: releases
  file: my-special-way.apk
  skip_cleanup: true
  on:
    repo: myspecialway/my-special-way-android
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: YeUagAU1NMujqW90CuutO0OypG39wtD9kOWEfu8xDIHv0ydCnGrGNIri0sPEwrazJjc/+SJHB52ePaoaSKyWnzw6ft1QsFCnsBx2a3y2hGMJ8eWuXRRHjRP6NkbDhnYBhUFZwwPiUupUieFd5MsyoM7hi6iXvM908arNTxYAwEkFBXNl45c6wpLxi9w8pE2L3CZbyNHS2yQ1Z5JQF6cw3m0qYr7t7/2FTOApoTmvSogTrNvYDrbCrzi+dwUnR5+aMxrUcyxJh6b8sT1/CZ9WzP3mBxoHoi06K5rFcIM7PT40xrIM/vzfaaggA7xPlHFVJbpCWivJAQrwtgov4P0N9d9k3BAYkdbKOpJYrS+dC+HyNcbJ7/BhMog31hVcjf9rwEzVkR6k6DZDkAxRv8cAwy7lh38TEQ/npQSegGGg/QWvG3FRq+ratj0WAkYcIIp+BcLG/kGNdkBmq2mXsUZVFdOJsue/1t6JznuDLOcjyqRSS7kw7HkBTwzWBXjGqVOPBd9V2dymSn9NNOUU+N+XrrtwNRx0BdHSx1t6Qh+eHm9xkIZ31JiwVjCcC89/J2G+ikm3AD79teOXoc7o0RgEvDYXYhLy6xMLA0oiwjBitv8NCIPYsvJJ7ke8pOWEQyxRV1bxpQKxRwyXldrblVX8BkfDOw1MEov6avNrdFFeKZ4=
notifications:
  slack:
    rooms:
    - secure: kxmck/5Yw2TCPXWOnN3T4xnCurs5gb48qbpdLx7oCYFAZVdt1HEv0yxkUimRzWngPLBpQkIFJ/2v+gsOimcuGFhHVl1DXlLp28BdIajGhWwsvKHmJE2i5QELzhpXKmdRrXdDGllfp59QCsTth+Suj58sClOOtWaPOJB+kAbKLy7jFufRHT+O4olfL2sX5G9YZirLEwtdTXecS1pW8gQxhJb/AR9t2IlCrW4nMNa78LZWo6eaeRT2sd6DgNCC1EX9HCSn+i5q2p6kzd7Xd6g55xRJr5A6NSsE91o1uX40oH91s2H8714mdRO8k2wVS2pK8g6asTSh5LMRkcp4FzXUAJv4mXt9tsIalyEk08de9pk+9iy4Z4mCSPpaxuRQP4pFi3nFCEDue/sTjBpHzQoWs2G0DfUp6VkXiDlFzc+92qcz5PgJO2Md9LDZPxRlM5BIpR4aQhvqig9qKmXmvxNEHwgpGlmlGB5EH1jv0fKHrzJW9Tn4xBsuO+zKZ2tUt0q/oo3yAXLKQmZ9JCeUyOR9RTbizZ6+zRjQS6plkkt7+HLXMHPrPF/FVj9g2/jXa+LbX0f+dzmc0OcAhDT/V5PXYkERg8ksA0YJ0Mau69vYo1QSIp+vX1ZOAS7iVkoyqDSJV+cczcp0VFuJF2y5pJouIk6wXb0PruXDfHaxhOtgCLo=
    - secure: VTt7ltGBqqiG8s4oXLJ9kBfu7visaAuBpM9ATNRM6nKEubXif1gC94W2KK0aYqW0FnqjD2zQBmmH9qfV9IMDKkXSTK/POsRL0lDhmwnsYx0YT0oAJhWCKFkQoEh/hJz/ZuzntYaQnlFpYHGXCFBeyZCafyXHRFx2FLvMCKZCQ+UGSiwnxcxonP0tTy9HX8pT8mnfUKK2LJo3jg6bpfcTArEm+qauMbTBmYZoOWO3SzuMDiac7NHkmBcCaPdcIwZRCTBAIZDp2tJ92doHgSNeG1+Ea+zlLQnRydjQZri214K9ey5hOtIH6Waok11xiMpOtTl4wFTY1hk7qu9ugKe6FPMWn84zvgD+P/9RkL7f54bSZJxN0K3h1RaEi3tnY0KVlnphR3uZIKz9DF+rPv5VqBQREuwEsrWxJCNVjcncAEoTBZH/aGxUcr2XrEGtRAy0u7940bI+Gdnr2QzhwLUpBDgulNhLTF+gMhECaPZksjzgUL2FuoH4Us4ZRLB3VCveHvIffzJIqIw20CML9obGWgYOAdSbcyQ4//g+lJuKR/Kk097j2Y8mJnIkGaEa1cpw+4nTttGNhE9Z8xY7qhHOhpqdkGJHZycGWj7I6aIKkl4nwUwLyNna1MnGkOYxsEr+/2NB5lVB228J6/fClFMFRMoyMppAqabXL/wIUNHjQgY=
  webhooks:
    urls:
      secure: RwTBd9M53CGfQ14e9K+JgqKPf4KxULDQXX2FXdYFcmhkVLXpKk0zo5R64v4b7wQ8L47VHPSpvIBoDGOItHix5ASi61O5NGpntSDCJfJAlw6H+9haGerCUkLX1PovUZ847bZ3E6zPNsEJhf3vk9+qfFmVDtjlX9dgwq/RumwUZjrXCSgDbYBLfg7FrvjBegNimGoXZvNi45VCVubaFpEZZM+Ky3falTv0IXJaoXWTmkkcRQxihzr6W5HTiIn7PuxDy2wivEOAdvW91dhRcxQZR+3JMxdzC0qooO53utoMOw2/5Ey0WkMovVbV61j5gBp7tOfxq5Fq7ChGSLGCYa+9r/n3a1izwe8AauT58AAqemz4sx1ydgQQtUVU4hvBradR8nP11/mK7v6Doy6hCM005D2XSGJfg7R1k4xRP4DHTGXtuhBneyYzsc/TAR+ODzH3qf+vz+JP6JLqQSr9c4TwNIDue9xqFPktWulxoiIwVj3qLO5otUJDsXNe79WpzoJueaE0K98OJPMEY2/0JutUAP0bpVI++Pa8eOzornceF4Oa8kc3xuiejSpuJS0nrZs4ZfYRkRvj6wtWR9fMc69RxlqzmxXcef9iLcxtRyjFQ7UXZQAyoJAq4gxFbIXiBazyA9Dvm7d3LCfwe0XeGJiQSJDC3OPKTIg6Ns6iEPUWbvo=
    on_success: never
    on_failure: always
